MovieApp/MovieApp/Models/ErrorViewModel.cs
using System;

namespace MovieApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieApp/MovieApp/Controllers/FrontPageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Models;
using LOGIC;
using TMDbLib.Objects.General;
using TMDbLib.Objects.Search;


namespace MovieApp.Controllers
{
    public class FrontPageController : Controller
    {
        public IActionResult Index()
        {
            MovieContainer allTrendingMovies = new MovieContainer();
            SearchContainer<SearchMovie> movies = allTrendingMovies.GetAllTrendingMovies();

            List<SearchMovie> listAsString = movies.Results.ToList();



            ViewData["PopulairMovies"] = listAsString;

            return View(listAsString);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieApp/MovieApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FACTORYVIEW;
using MODELS;
using INTERFACESDAL.STRUCTS;
using INTERFACESVIEW;
using LOGIC;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{


    public class LoginController : Controller
    {
        public LoginController(AuthenticationService authenticationService)
        {
            AuthenticationService = authenticationService;
        }

        public AuthenticationService AuthenticationService { get; }

        //private ILoginController loginController;


        public IActionResult LoginPage()
        {
            return View(new UserModel());
        }

        [HttpPost]
        public IActionResult LoginPage(UserModel model)
        {
            

            if (AuthenticationService.LoginCheck(model.Username, model.Password))
            {
                IUserView userModel = UserFactoryView.CreateUserContainerLogic().GetUserByName(model.Username);

                //slaat de user op in sessions
                HttpContext.Session.SetInt32("UserId", userModel.Id);
                HttpContext.Session.SetString("Username", userModel.Username.ToString());
                HttpContext.Session.SetString("UserLvl", userModel.Email);

                ViewBag.TestSession = HttpContext.Session.GetString("Username");

                ViewBag.LoginData = "Login Succesfull";
            }
            else
            {
                ViewBag.LoginData = "Login Unsuccesfull";
            }

            return View();
        }
    }
}

MovieApp/MovieApp/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using FACTORYVIEW;
using INTERFACESDAL.STRUCTS;
using INTERFACESVIEW;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult MoviePage(int movieId)
        {
            MovieDTO movie = new MovieDTO();
            List<IReview> reviewList = new List<IReview>();

            if (movieId == 0)
            {
                movie = MovieContainerFactoryView.CreateMovieContainerView().GetMovieById(Convert.ToInt32(TempData["MovieId"]));
                reviewList = UserFactoryView.CreateUserView().GetAllReviewsFromMovie(Convert.ToInt32(TempData["MovieId"]));
            }
            else
            {

                movie = MovieContainerFactoryView.CreateMovieContainerView().GetMovieById(movieId);
                reviewList = UserFactoryView.CreateUserView().GetAllReviewsFromMovie(movieId);
            }



            ViewData["movieName"] = movie.Name;
            ViewData["movieDescription"] = movie.Description;
            ViewData["movieId"] = movie.Id;

            return View(reviewList);
        }

        [HttpPost]
        public IActionResult MoviePage()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("Username")))
            {
                return RedirectToAction("LoginPage", "Login");
            }

            string username = HttpContext.Session.GetString("Username");

            //if movie is not in watchlist add it to watchlist

            UserFactoryView.CreateUserContainerLogic().GetUserByName(username);

            if (true/*WatchlistFactoryView.CreateWatchListView().CheckIfMovieIsInWatchlist()*/)// movie is not in watchlist
            {
                //add to watchlist
            }



            return View();
        }
        
    }
}

MovieApp/MovieApp/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FACTORYVIEW;
using Microsoft.AspNetCore.Mvc;
using MODELS;
using INTERFACESDAL.STRUCTS;
using INTERFACESVIEW;
using LOGIC;

namespace MovieApp.Controllers
{
    public class RegisterController : Controller
    {
        

        public IActionResult NewAccount()
        {
            return View(new UserModel());
        }

        [HttpPost]
        public IActionResult NewAccount(UserModel model)
        {
            
            UserDTO user = new UserDTO();

            user.Name = model.Name;
            user.Email = model.Email;
            user.Username = model.Username;
            user.Password = model.Password;

            

            if (UserFactoryView.CreateUserContainerLogic().AddUser(user))
            {
                ViewBag.RegisterData = "Register Succesfull";
            }
            else
            {
                ViewBag.RegisterData = "Register Unsuccesfull";
            }

            return View();
        }
    }
}

MovieApp/MovieApp/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FACTORYVIEW;
using INTERFACESDAL.STRUCTS;
using INTERFACESVIEW;
using LOGIC;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MODELS;

namespace MovieApp.Controllers
{
    public class ReviewsController : Controller
    {
        public IActionResult ReviewPage(int movieId,string movieName)
        {
            ViewData["Id"] = movieId;
            ViewData["Name"] = movieName;




            return View();
        }

        [HttpPost]
        public IActionResult ReviewPage(ReviewModel reviewModel)
        {
            IReview iReview = new Review();

            iReview.Title = reviewModel.Title;
            iReview.Recommended = reviewModel.Recommended;
            iReview.Description = reviewModel.Description;
            iReview.Rating = reviewModel.Rating;
            iReview.MovieId = reviewModel.MovieId;
            iReview.UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId")); 

            


            if (UserFactoryView.CreateUserView().AddReview(iReview))
            {
                ViewBag.RegisterData = "Review added";
            }
            else
            {
                ViewBag.RegisterData = "Adding the review was unsuccessful";
            }

            TempData["MovieId"] = iReview.MovieId;
            return RedirectToAction("MoviePage","Movie");
        }
    }
}

MovieApp/MovieApp/Views/FrontPage/index.cshtml
@{
    ViewData["Title"] = "FrontPage";
}

<h2>FrontPage</h2>


@model List<TMDbLib.Objects.Search.SearchMovie>


<div class="AllMovies">
    @foreach (var item in Model)
    {

        <div class="MovieBlock">
            <a href='@Url.Action("MoviePage", "Movie", new { movieId = item.Id })'>
                <img src="~/images/Deadpool.jpg" width="200" height="300" class="MovieImage">
                <div class="MovieTitle">@item.Title</div>
            </a>
        </div>
    }

</div>

MovieApp/MovieApp/Views/Login/LoginPage.cshtml
@model MODELS.UserModel
@{
    ViewData["Title"] = "LoginPage";
}

<h2>LoginPage</h2>

<form asp-action="LoginPage" asp-controller="Login">
    <p>Username:<input asp-for="Username" type="text" /></p>
    <p>Password:<input asp-for="Password"type="password" /></p>

    <p><input type="submit" name="Login"/></p>

    <p>Make a new account <a href="@Url.Action("NewAccount", "Register")">here</a></p>

    <p>@ViewBag.LoginData</p>

    @*<p>@ViewBag.TestSession</p>*@
</form>

MovieApp/MovieApp/Views/Movie/MoviePage.cshtml
@model List<INTERFACESVIEW.IReview>
@{
    ViewData["Title"] = "Movie";
}

<h2>Movie</h2>



<p>@ViewData["movieName"].ToString()</p>
@*@ViewData["movieGenres"].ToString()*@
<p>@ViewData["movieDescription"].ToString()</p>
@*@ViewData["movieId"].ToString()*@


<p>Make a review on this movie<a href="@Url.Action("ReviewPage", "Reviews",new { movieId = @ViewData["movieId"], movieName = @ViewData["movieName"]})"> here</a></p>

<form asp-action="MoviePage" asp-controller="Movie">
    <p><input type="submit" name="AddToWatchlist" /></p>

    <p>@ViewBag.WatchListData</p>

</form>


<h3>Reviews</h3>
<div id="AllReviews">
    
    @foreach (var item in Model)
    {
        <div class="Review" style="border-bottom: 1px solid black;">
            <div>@item.Title</div>
            <div>@item.Rating/10</div><br />
            @if (@item.Recommended == true)
                {
            <div>Recommended</div><br />
                }
                else
                {
            <div>Not Recommended</div><br />
                }

            <div>@item.Description</div>
        </div>
    }
    
</div>

MovieApp/MovieApp/Views/Register/NewAccount.cshtml
@model MODELS.UserModel
@{
    ViewData["Title"] = "CreateAccount";
}

<h2>CreateAccount</h2>

<form asp-action="NewAccount" asp-controller="Register">
    <p>Name: <input asp-for="Name" type="text" /></p>
    <p>Email: <input asp-for="Email" type="text" /></p>
    <p>Username: <input asp-for="Username" type="text" /></p>
    <p>Password: <input asp-for="Password" type="password" /></p>

    <p><input type="submit" name="Create" /></p>

    <p>@ViewBag.RegisterData</p>

</form>

MovieApp/MovieApp/Views/Reviews/ReviewPage.cshtml
@model MODELS.ReviewModel

@{
    ViewData["Title"] = "ReviewPage";
}

<h2>ReviewPage</h2>

@*@ViewData["Id"].ToString()*@
@ViewData["Name"].ToString()

<form asp-action="ReviewPage" asp-controller="Reviews">
    <p>Title: <input asp-for="Title" type="text" /></p>
    <p>Recommended: <input asp-for="Recommended" type="checkbox" /></p>
    <p>Description: <input asp-for="Description" type="text" /></p>
    <p>Rating: <input asp-for="Rating" type="number" /></p>
    <p><input asp-for="MovieId" type="hidden" value="@ViewData["Id"]"/></p>

    <p><input type="submit" name="Create" /></p>

    <p>@ViewBag.RegisterData</p>

</form>

MovieApp/MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MovieApp</a>
            </div>
            
            <div class="navbar-collapse collapse">
                <div class="menuItems">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="FrontPage" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Account">Account</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Watchlist">Watchlist</a></li>
                        <li><a asp-area="" asp-controller="Login" asp-action="LoginPage">Login</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - MovieApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>